### ISSUE TITLE
MicrosliceReceiver fails for empty Microslices

### ISSUE THREAD

**Issue by oTTer-Chief** [cbm-fles/flesnet#1]
For empty ms (desc.size == 0) MicrosliceReceiver will try to assemble data buffer from two segments. This fails and result in an assertion. Tested with FLIB Server as data source.
Maybe it is sufficient to change:
        if (data_begin < data_end) {
to:
        if (data_begin <= data_end) {

**Comment by cuveland** [comment]
This issue is resolved by ace5afa2dbe6d1298e1081a2fda7396e7a9ede32.
